### ISSUE TITLE
Role Mapping Not Functional

### ISSUE THREAD

**Issue by mbrewster** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#16]
It appears that the role mapping as documented is not functional. I've tried deploying per your instructions, but the defined permissions by role are not applied. 

Based on the log it does appear that roles are applied on log-in:

2018-01-12 21:55:32,138+0000 INFO  [qtp1860348712-47]  Matt Brewster com.larscheidschmitzhermes.nexus3.github.oauth.plugin.GithubOauthAuthenticatingRealm - doGetAuthorizationInfo for user Matt Brewster with roles base2solutions/b2-devopsbase2solutions/team1base2solutions/team2

However, granting `nx-all` to `base2solutions/b2-devops` does not result in any granted permissions when I authenticate. 

Any ideas?

**Comment by tobilarscheid** [comment]
Hi Matt,

in general, the role mapping is functional - otherwise the plugin was pretty useless ;-)

If you double checked that everything is configured correctly, the only thing I can think of may be the dash in your team name - in the contexts where I used the plugin, the names never contained dashes as far as I remember. So maybe create a team without dash in the name and test wether that works - if yes, congrats for finding a bug!

Cheers,

Tobi

**Comment by schmitzhermes** [comment]
What we should - apart from the particular problem - fix anyways is this line: https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/blob/master/src/main/java/com/larscheidschmitzhermes/nexus3/github/oauth/plugin/GithubOauthAuthenticatingRealm.java#L79 
We should concatenate the roles with some kind of nice separator, preferably a `;`

**Comment by mbrewster** [comment]
I figured out the issue today - the `Role ID` needs to map to the team name and not the `Role Description` as noted in your screenshot. I'll create a PR to update.

**Comment by tobilarscheid** [comment]
aaaah, sneaky. thanks. I think in reality we never set `Role ID` and `Role Name` to different values - that's why we didn't catch that. PR is highly welcome!

**Comment by tobilarscheid** [comment]
once again thanks to @mbrewster for the heads up, the new documentation hopefully makes this a lot clearer.
