### ISSUE TITLE
Give the plugin a friendly name/ID

### ISSUE THREAD

**Issue by lobsterdore** [larscheid-schmitzhermes/nexus3-github-oauth-plugin#30]
I am writing a Groovy script to enable this plugin, due to this line here I have to use the rather verbose realm name of ```com.larscheidschmitzhermes.nexus3.github.oauth.plugin.GithubOauthAuthenticatingRealm``` in the script - https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/blob/master/src/main/java/com/larscheidschmitzhermes/nexus3/github/oauth/plugin/GithubOauthAuthenticatingRealm.java#L41

Other realm plugins seem to provide friendly names for use in Groovy scripts, could we have one for this plugin?

Example script:

```
import groovy.json.JsonSlurper
import org.sonatype.nexus.security.realm.RealmManager
import org.sonatype.nexus.security.realm.RealmConfiguration

parsed_args = new JsonSlurper().parseText(args)

def realmManager = container.lookup(RealmManager.class.getName());
RealmConfiguration realmConfig = realmManager.getConfiguration()
realmManager.enableRealm("com.larscheidschmitzhermes.nexus3.github.oauth.plugin.GithubOauthAuthenticatingRealm", parsed_args.enabled && parsed_args.enabled.toBoolean())
```

**Comment by tobilarscheid** [comment]
Hi @lobsterdore,
I actually like that our plugin has a fully qualified name - that way we can not run into conflicts with other oauth plugins. Also, I am a bit hesitant to change the name because I am not entirely sure what it will do to backwards compatibility / existing users. So from my (possibly biased) point of view your script looks absolutely fine the way it is. 

Side note: If you published your script somewhere, I would absolutely link to it from this repository as an alternative means of installation!

**Comment by lobsterdore** [comment]
OK no problem at all, I've published the script here:

https://gist.github.com/lobsterdore/bdfbd1df7987970afc843a167218174d

**Comment by lobsterdore** [comment]
Closing this for now
